version: '3'

services:
  backend:
    build: backend
    depends_on:
      - postgres
    command: yarn start:dev
    working_dir: /app
    environment:
      NODE_ENV: development
      PORT: 3001
      JWT_SECRET: 'Glaysinho'
      PGUSER: postgres
      PGHOST: postgres
      PGPASSWORD: dev
      PGDATABASE: postgres
      PGPORT: 5432
      VAPID_PRIVATE_KEY: dBMDY6HXmidQ2icjp06X_OuOOSoBkdGXvOq7rUeTIQo
      VAPID_PUBLIC_KEY: BD9G7lE3f2OTf-8qRXWULCWxpJQhA_-qtbqosH9F27sGyxGRbcwvW-DciQu9YKaCn568ZuYGK-VS5HuGGEbd5Yo
      HOST: http://localhost:3001
    volumes:
      - ./backend:/app
    ports:
      - 3001:3001

  frontend:
    build: frontend
    depends_on:
      - backend
    command: yarn dev --host 0.0.0.0
    working_dir: /app
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - ./servers.json:/pgadmin4/servers.json

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: dev
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
  
  sonarqube:
    image: sonarqube
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
    ports:
      - 9000:9000

volumes:
  postgres:
