version: '3'

services:
  app:
    build: .
    depends_on:
      - postgres
    command: yarn start:dev
    working_dir: /app
    environment:
      NODE_ENV: development
      PORT: 3001
      JWT_SECRET: 'Glaysinho'
      PGUSER: postgres
      PGHOST: postgres
      PGPASSWORD: dev
      PGDATABASE: postgres
      PGPORT: 5432
    volumes:
      - .:/app
    ports:
      - 3001:3001

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - ./servers.json:/pgadmin4/servers.json

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: dev
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata

volumes:
  postgres:
